-- Sample stock movements using real product IDs from database
INSERT INTO inv_stock_movements (product_id, type, quantity, reference, notes, created_at) VALUES
(4, 'inbound', 50, 'PO-001', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 30 DAY)),
(5, 'inbound', 30, 'PO-001', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 30 DAY)),
(4, 'outbound', 10, 'SALE-001', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 30 DAY)),
(5, 'outbound', 15, 'SALE-002', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 29 DAY)),
(6, 'inbound', 100, 'PO-002', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 29 DAY)),
(7, 'outbound', 20, 'SALE-003', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 29 DAY)),
(4, 'outbound', 8, 'SALE-004', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 28 DAY)),
(29, 'inbound', 40, 'PO-003', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 28 DAY)),
(4, 'outbound', 12, 'SALE-005', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 27 DAY)),
(30, 'inbound', 60, 'PO-004', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 27 DAY)),
(5, 'outbound', 5, 'SALE-006', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 27 DAY)),
(5, 'outbound', 25, 'SALE-007', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 26 DAY)),
(6, 'outbound', 18, 'SALE-008', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 26 DAY)),
(4, 'outbound', 22, 'SALE-009', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 25 DAY)),
(7, 'inbound', 80, 'PO-005', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 25 DAY)),
(4, 'inbound', 45, 'PO-006', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 24 DAY)),
(5, 'outbound', 30, 'SALE-010', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 24 DAY)),
(4, 'outbound', 14, 'SALE-011', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 23 DAY)),
(8027, 'inbound', 70, 'PO-007', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 23 DAY)),
(5, 'outbound', 35, 'SALE-012', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 22 DAY)),
(6, 'outbound', 12, 'SALE-013', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 22 DAY)),
(4, 'outbound', 20, 'SALE-014', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 21 DAY)),
(29, 'outbound', 18, 'SALE-015', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 21 DAY)),
(5, 'inbound', 50, 'PO-008', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 20 DAY)),
(7, 'outbound', 40, 'SALE-016', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 20 DAY)),
(4, 'outbound', 25, 'SALE-017', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 19 DAY)),
(8028, 'outbound', 35, 'SALE-018', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 19 DAY)),
(5, 'inbound', 90, 'PO-009', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 18 DAY)),
(6, 'outbound', 28, 'SALE-019', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 18 DAY)),
(4, 'outbound', 18, 'SALE-020', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 17 DAY)),
(29, 'outbound', 15, 'SALE-021', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 17 DAY)),
(5, 'outbound', 22, 'SALE-022', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 16 DAY)),
(8029, 'inbound', 55, 'PO-010', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 16 DAY)),
(4, 'inbound', 35, 'PO-011', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 15 DAY)),
(7, 'outbound', 32, 'SALE-023', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 15 DAY)),
(8027, 'outbound', 40, 'SALE-024', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 14 DAY)),
(5, 'outbound', 20, 'SALE-025', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 14 DAY)),
(6, 'inbound', 65, 'PO-012', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 13 DAY)),
(4, 'outbound', 25, 'SALE-026', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 13 DAY)),
(29, 'outbound', 30, 'SALE-027', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 12 DAY)),
(8030, 'inbound', 75, 'PO-013', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 12 DAY)),
(5, 'outbound', 18, 'SALE-028', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 11 DAY)),
(30, 'outbound', 28, 'SALE-029', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 11 DAY)),
(4, 'outbound', 22, 'SALE-030', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 10 DAY)),
(7, 'inbound', 48, 'PO-014', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 10 DAY)),
(8028, 'outbound', 35, 'SALE-031', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 9 DAY)),
(5, 'outbound', 15, 'SALE-032', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 9 DAY)),
(6, 'outbound', 24, 'SALE-033', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 8 DAY)),
(8029, 'inbound', 42, 'PO-015', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 8 DAY)),
(4, 'inbound', 60, 'PO-016', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 7 DAY)),
(29, 'outbound', 28, 'SALE-034', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 7 DAY)),
(5, 'outbound', 20, 'SALE-035', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 6 DAY)),
(30, 'outbound', 38, 'SALE-036', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 6 DAY)),
(7, 'outbound', 15, 'SALE-037', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 5 DAY)),
(8030, 'inbound', 58, 'PO-017', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 5 DAY)),
(4, 'outbound', 30, 'SALE-038', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 4 DAY)),
(7, 'outbound', 25, 'SALE-039', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 4 DAY)),
(8027, 'inbound', 52, 'PO-018', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 3 DAY)),
(5, 'outbound', 18, 'SALE-040', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 3 DAY)),
(6, 'outbound', 22, 'SALE-041', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(30, 'outbound', 20, 'SALE-042', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(4, 'outbound', 35, 'SALE-043', 'Walk-in sale', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(29, 'inbound', 70, 'PO-019', 'Purchase order received', DATE_SUB(NOW(), INTERVAL 1 DAY));